import './globals.css'
import Contact from './contact/page';
import Header from '@/components/Header'
import Footer from '@/components/Footer'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex flex-col w-full mx-auto p-8'>
         <Header />
            <main className='grow'>{children}</main>
         <Footer/>
      </body>
    </html>
  )
}
